# Generated by Django 5.2.1 on 2025-05-26 16:31

import pdf_processing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='modified_file',
            field=models.FileField(blank=True, null=True, upload_to=pdf_processing.models.user_directory_path),
        ),
    ]
